### ISSUE TITLE
image upload max size

### ISSUE THREAD

**Issue by Gossage566** [AzCreativeWorld/Dropzone-with-Image-Resizer#2]
The project is very helpful thanx. I am trying to increase the maximum image upload size from the project default that is 2 MB to 5mb.when I try to increase it it displays an error.plz help

**Comment by mianzaid** [comment]
Just change the value of the below line in index.php
maxFilesize: 2, // MB
**TO**
maxFilesize: 5, // MB

**Comment by Gossage566** [comment]
i have tried to do so but it shows some error  pls look on this link it
demonstrates well  https://www.youtube.com/watch?v=DyOG6TruINo thank you
