### ISSUE TITLE
Gif

### ISSUE THREAD

**Issue by Jefekoi** [AzCreativeWorld/Dropzone-with-Image-Resizer#5]
Hello and thank you for this excellent program
Just one question: animated gif lose animation
How to fix the problem? 

Sorry I'm French, I don't speak English

**Comment by mianzaid** [comment]
Hi, Gif is not a single image it is a combination of multiple images, to keep the animation in resizing you need to resize each frame one by one and then combine all the frames.
I will try to fix the GIF problem as well.

Thank you.

**Comment by Jefekoi** [comment]
Merci MianZaid

**Comment by Jefekoi** [comment]
Vraiment bien vos programmes, je viens de trouver un de vos programme suite à ma demande : https://learncodeweb.com/web-development/drag-drop-images-with-bootstrap-4-and-reorder-using-php-jquery-and-ajax/

Really good your programs, I just found one of your program following my request: https://learncodeweb.com/web-development/drag-drop-images-with-bootstrap-4-and-reorder-using-php- jquery-and-ajax /

**Comment by mianzaid** [comment]
Not supported with this CLASS.
