### ISSUE TITLE
variable value

### ISSUE THREAD

**Issue by PcKiyatrist** [AzCreativeWorld/Dropzone-with-Image-Resizer#6]
How can I save the variable value I obtained on the index.php page to the database.

<input type="hidden" name="producti_id" value="<?php echo $_GET['product_id'];  ?>">
<div class="form-group">
<button type="submit" id="add_file" class="btn btn-primary" name="submit"><i class="fa fa-upload"></i> Upload File(s)</button>        
 </div>

How can I add the product_id value in the actions.ajax.php page and save it to the database?

**Comment by mianzaid** [comment]
Learn the basics of PHP.
